# docker-compose.yml

version: "3.8"

services:
  # MongoDB Database Service
  mongo:
    image: mongo:latest
    container_name: notes-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - notes-app-network

  # FastAPI Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-backend
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - notes-app-network

# Define the volume for data persistence
volumes:
  mongo-data:

# Define the shared network
networks:
  notes-app-network:
    driver: bridge